#include "rbpf_jit_compiler.h"

static __attribute__((always_inline)) inline unsigned int eval_input_len(struct jit_state* st)
{
  return (*st).input_len;
}

static __attribute__((always_inline)) inline unsigned long long eval_input_ins(struct jit_state* st, unsigned int idx)
{ //print_jit_state(st);
  return *((*st).input_ins + idx);
}

static __attribute__((always_inline)) inline unsigned int get_dst(unsigned long long ins)
{
  return (unsigned int) ((ins & 4095LLU) >> 8LLU);
}

static __attribute__((always_inline)) inline unsigned int get_src(unsigned long long ins)
{
  return (unsigned int) ((ins & 65535LLU) >> 12LLU);
}

static __attribute__((always_inline)) inline unsigned int eval_arm_ofs(struct jit_state* st)
{
  return (*st).tp_bin_len;
}

static __attribute__((always_inline)) inline void add_key_value(struct jit_state* st, unsigned int pc, unsigned int ofs0, unsigned int ofs1){
  (*st).tp_kv[pc].arm_ofs = ofs0;
  (*st).tp_kv[pc].alu32_ofs = ofs1;
  return ;
}

static __attribute__((always_inline)) inline _Bool eval_use_IR11(struct jit_state* st){
  return (*st).use_IR11;
}

static __attribute__((always_inline)) inline void upd_IR11_jittedthumb(struct jit_state* st, _Bool f){
  (*st).use_IR11 = f;
  return ;
}

static __attribute__((always_inline)) inline void add_jited_bin(struct jit_state* st, unsigned int ins){
  //if ((*st).tp_bin_len < JITTED_LIST_MAX_LENGTH){
    (*st).tp_bin[(*st).tp_bin_len] = ins;
    (*st).tp_bin_len = (*st).tp_bin_len + 1U;
    return ; /*
  }
  else {
    // *((*st).flag) = vBPF_ILLEGAL_ARM_LEN;
    return ;
  } */
}

static __attribute__((always_inline)) inline _Bool eval_load_regset(struct jit_state* st, unsigned int r){
  return (*st).ld_set[r];
}

static __attribute__((always_inline)) inline _Bool eval_store_regset(struct jit_state* st, unsigned int r){
  return (*st).st_set[r];
}

static __attribute__((always_inline)) inline void upd_load_regset(struct jit_state* st, unsigned int r){
  (*st).ld_set[r] = 1; //set to true
  return ;
}

static __attribute__((always_inline)) inline void upd_store_regset(struct jit_state* st, unsigned int r){
  (*st).st_set[r] = 1;
  return ;
}

static __attribute__((always_inline)) inline void reset_init_jittedthumb(struct jit_state* st){
  (*st).use_IR11 = 0;
  for (unsigned int i = 0; i < 11; i ++) { (*st).ld_set[i]  = 0; (*st).st_set[i]  = 0; }
  return ;
}

// a recursion implementation of power2 to replace pow(2, _) from math.h because CompCert doesn't support math.h
static __attribute__((always_inline)) inline unsigned int power2(unsigned int width){
  if (width == 0U) {
    return 1U;
  }
  else {
    return 2U * power2(width - 1U);
  }
}

static __attribute__((always_inline)) inline unsigned int decode_thumb(unsigned int ins, unsigned int from, unsigned int size){
  return ( (ins >> from) & (power2(size) - 1U) );
}

static __attribute__((always_inline)) inline unsigned int encode_thumb(unsigned int v, unsigned int ins, unsigned int from, unsigned int size){
  unsigned int mask;
  mask = (power2(size) - 1U) << from;
  return ( ((v & (power2(size) - 1U)) << from) | (ins & (~mask)) );
}

static __attribute__((always_inline)) inline _Bool ins_is_bpf_alu32(unsigned long long ins){
  unsigned char op;
  op = (unsigned char) (ins & 255LLU);
  return (op == 4) || (op == 12) ||
  	 (op == 20) || (op == 28) ||
  	 (op == 36) || (op == 44) ||
  	 (op == 60) ||
  	 (op == 68) || (op == 76) ||
  	 (op == 84) || (op == 92) ||
  	 (op == 108) || (op == 124) ||
  	 (op == 132) ||
  	 (op == 164) || (op == 172) ||
  	 (op == 180) || (op == 188) ||
  	 (op == 204);
}
static __attribute__((always_inline)) inline _Bool ins_is_bpf_jump(unsigned long long ins){
  unsigned char op;
  op = (unsigned char) (ins & 255LLU);
  return (op == 5) ||
  	 (op == 21) || (op == 29) ||
  	 (op == 37) || (op == 45) ||
  	 (op == 53) || (op == 61) ||
  	 (op == 69) || (op == 77) ||
  	 (op == 85) || (op == 93) ||
  	 (op == 101) || (op == 109) ||
  	 (op == 117) || (op == 125) ||
  	 (op == 165) || (op == 173) ||
  	 (op == 181) || (op == 189) ||
  	 (op == 197) || (op == 205) ||
  	 (op == 213) || (op == 221);
  
}

/*******************below code are automatically generated by dx (after repatch) ***************************/
